version: '3.9'

services: 
    mongo:
        image: mongo
        restart: always
        container_name: mongo_server
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        networks:
            - trumpee_backend_vpn
        ports:
            - 23001:27017

    gateway_api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: trumpee_gateway_api
        networks:
            - trumpee_backend_vpn
        ports:
            - 22001:22001

networks:
    trumpee_backend_vpn:
        name: trumpee_backend_vpn
