version: '3.9'

services: 
    mongo:
        image: mongo
        restart: always
        container_name: mongo_server
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        networks:
            - trumpee_backend_vpn
        ports:
            - 23001:27017

    rabbitmq:
        image: masstransit/rabbitmq
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - trumpee_backend_vpn
        restart: unless-stopped

networks:
    trumpee_backend_vpn:
        name: trumpee_backend_vpn
