name: Build and Test Backend Solution

on:
  push:
    paths:
      - '**/src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ secrets.DOTNET_VERSION }}

      - name: Build Solution
        run:  dotnet build Gateway.sln -c Release

      - name: Test
        run: dotnet test --no-build -c Release -v normal Gateway.sln